# Generated manually for the initial Parallax event schema.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Track', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100,unique=True)),('description',models.TextField()),('problem_statements',models.TextField()),('is_published',models.BooleanField(default=False)),('is_problem_live',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Participant', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('full_name',models.CharField(max_length=150)),('email',models.EmailField(max_length=254,unique=True)),('phone_number',models.CharField(blank=True,max_length=15)),('college_name',models.CharField(blank=True,max_length=200)),('reg_number',models.CharField(blank=True,max_length=30,null=True)),('is_profile_complete',models.BooleanField(default=False)),('is_team_leader',models.BooleanField(default=False)),('payment_proof',models.FileField(blank=True,null=True,upload_to='payment-proofs/')),('approval_status',models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected')],default='PENDING',max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='participant',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Team', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('team_name',models.CharField(max_length=100,unique=True)),('team_code',models.CharField(blank=True,max_length=10,unique=True)),('invoice_number',models.CharField(blank=True,max_length=100,null=True)),('status',models.CharField(choices=[('PENDING','Pending Review'),('APPROVED','Approved'),('REJECTED','Rejected')],default='PENDING',max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('leader',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='led_team',to='core.participant')),('track',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='teams',to='core.track'))]),
        migrations.AddField(model_name='participant',name='team',field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='members',to='core.team')),
        migrations.CreateModel(name='Review', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('description',models.TextField(blank=True)),('scheduled_at',models.DateTimeField()),('max_marks',models.PositiveIntegerField(default=100))]),
        migrations.CreateModel(name='Prize', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('first_place',models.CharField(default='Pending sponsorship confirmation',max_length=200)),('second_place',models.CharField(default='Pending sponsorship confirmation',max_length=200)),('third_place',models.CharField(default='Pending sponsorship confirmation',max_length=200)),('updated_at',models.DateTimeField(auto_now=True)),('track',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='prize',to='core.track'))]),
        migrations.CreateModel(name='Announcement', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=200)),('body',models.TextField()),('is_pinned',models.BooleanField(default=False)),('send_email',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='announcements',to=settings.AUTH_USER_MODEL))], options={'ordering':['-is_pinned','-created_at']}),
        migrations.CreateModel(name='Marks', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('score',models.DecimalField(decimal_places=2,max_digits=6)),('remarks',models.TextField(blank=True)),('updated_at',models.DateTimeField(auto_now=True)),('graded_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='graded_marks',to=settings.AUTH_USER_MODEL)),('review',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='marks',to='core.review')),('team',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='marks',to='core.team'))], options={'unique_together':{('team','review')}}),
    ]
