# Generated by Django 5.0.14 on 2026-07-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_problem_live',
            field=models.BooleanField(default=False, help_text='Make this track problem statement visible to participants.'),
        ),
    ]
