# Generated by Django 5.0.14 on 2026-07-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_track_is_problem_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='approval_status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')],
                default='PENDING',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment-proofs/'),
        ),
    ]
