# Generated by Django 5.0.14 on 2026-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_track_is_problem_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved')], default='PENDING', max_length=10),
        ),
    ]
