# Generated by Django 5.0.14 on 2026-07-23 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_participant_approval_status_alter_team_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=150)),
                ('reg_number', models.CharField(max_length=50, verbose_name='Registration number')),
                ('graduation_year', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=120)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Not started'), ('PAY_LATER', 'Pay later'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('registration_email_sent', models.BooleanField(default=False)),
                ('payment_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slot_capacity', models.PositiveIntegerField(default=0, help_text='Total teams allowed to book this problem statement.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statement_slots', to='core.track')),
            ],
            options={
                'ordering': ['track__name', 'code', 'title'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='problem_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_teams', to='core.problemstatement'),
        ),
    ]
