# Generated by Django 5.0.14 on 2026-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaderregistration_problemstatement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderregistration',
            name='city',
        ),
        migrations.AddField(
            model_name='leaderregistration',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderregistration',
            name='team_members',
            field=models.TextField(default='', help_text='Names of the team members, one per line or comma-separated.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderregistration',
            name='team_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
